[workspace]

members = [
    "variavels",
    "vetores",
    "enumerados",
    "structs",
    "funcoes",
    "traits",
    "condicao_e_loops",
    "iteradores",
    "ponteiros_inteligentes",
    "colecao_hash_map",
    "into_e_from",
    "ownership_e_borrowing",
]
